apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: default-httproute
  namespace: whereami
spec:
  parentRefs:
  - name: external-http
    namespace: whereami
  rules:
  - backendRefs:
    - group: net.gke.io
      kind: ServiceImport
      name: whereami-flip
      port: 80
      weight: 50
    - group: net.gke.io
      kind: ServiceImport
      name: whereami-flop
      port: 80
      weight: 50
